version: "3.8"
services:
    frigate:
        build:
            context: .
        container_name: frigate1
        restart: unless-stopped
        ports: 
          - "80:80"
          - "8080:8080"



