name: deploycode workflow

on:
  push:
    branches:
      - master

jobs:
  deploy-to-prod:
    runs-on: frigateai-v2

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Manage Docker
      run: |
        cd $GITHUB_WORKSPACE
        sudo docker-compose down 
        sudo docker-compose up -d --build